Tried adding magma calls for HIOP interface. Build is failing.
/usr/bin/ld: ../src/opflow/libopflow.a(opflow-hiop.cpp.o): undefined reference to symbol 'magma_init'
/share/apps/magma/2.5.2/cuda10.2/lib/libmagma.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [applications/app_opflow] Error 1
make[1]: *** [applications/CMakeFiles/app_opflow.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/bin/ld: ../src/opflow/libopflow.a(opflow-hiop.cpp.o): undefined reference to symbol 'magma_init'
/share/apps/magma/2.5.2/cuda10.2/lib/libmagma.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [applications/app_scopflow] Error 1
make[1]: *** [applications/CMakeFiles/app_scopflow.dir/all] Error 2
/usr/bin/ld: ../src/opflow/libopflow.a(opflow-hiop.cpp.o): undefined reference to symbol 'magma_init'
/share/apps/magma/2.5.2/cuda10.2/lib/libmagma.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [applications/app_tcopflow] Error 1
make[1]: *** [applications/CMakeFiles/app_tcopflow.dir/all] Error 2
make: *** [all] Error 2